# Generated by Django 2.0.3 on 2018-09-16 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appCode', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conexion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fecha', models.CharField(max_length=50)),
                ('FK_idEthernet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCode.Ethernet')),
                ('FK_idSimCard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCode.SimCard')),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accion', models.CharField(max_length=50)),
                ('Fecha', models.CharField(max_length=50)),
                ('Donde', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=50)),
                ('Nombre', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='log',
            name='FK_idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Usuario'),
        ),
        migrations.AddField(
            model_name='conexion',
            name='FK_idUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Usuario.Usuario'),
        ),
        migrations.AddField(
            model_name='conexion',
            name='FK_idWifi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appCode.Wifi'),
        ),
    ]
